language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t andrewtdinh/react-test -f ./client/Dockerfile../client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andrewtdinh/react-test npm andrewtdinh/react-test

after_success: 
  - docker build -t andrewtdinh/multi-client ./client
  - docker build -t andrewtdinh/multi-nginx ./nginx
  - docker build -t andrewtdinh/multi-server ./server
  - docker build -t andrewtdinh/multi-worker ./worker