language: generic
sudo: required
services:
  - docker

before_install: 
  - docker build -t andrewtdinh/react-test -f ./client/Dockerfile../client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andrewtdinh/react-test npm andrewtdinh/react-test

after_success: 
  - docker build -t andrewtdinh/multi-client ./client
  - docker build -t andrewtdinh/multi-nginx ./nginx
  - docker build -t andrewtdinh/multi-server ./server
  - docker build -t andrewtdinh/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take built images and push them to Docker hub 
  - docker push andrewtdinh/multi-client
  - docker push andrewtdinh/multi-nginx
  - docker push andrewtdinh/multi-server
  - docker push andrewtdinh/multi-worker
